apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
generatorOptions:
  disableNameSuffixHash: true
  immutable: true
configMapGenerator:
  - name: grafana-dashboards
    options:
      labels:
        grafana.org/dashboards: "true"
    files:
      - overview.json
