run:
  allow-parallel-runners: false
  allow-serial-runners: true
  concurrency: 0
  timeout: 10m
  tests: true
  modules-download-mode: readonly
output:
  formats:
    - format: colored-line-number
      path: stderr
  sort-results: true
  sort-order:
    - severity
    - linter
    - file
  show-stats: true
#linters:
#  enable-all: true
#  disable:
