apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: devbot
build:
  artifacts:
  - image: europe-docker.pkg.dev/arikkfir/public/devbot/api
    context: ./api
    docker:
      dockerfile: Dockerfile.dev
  - image: europe-docker.pkg.dev/arikkfir/public/devbot/portal
    context: ./portal
    docker:
      dockerfile: Dockerfile.dev
    sync:
      manual:
        - src: public/**
          dest: /workspace/public/
        - src: src/**
          dest: /workspace/src/
          strip: src/
  local:
    push: false
deploy:
  kustomize:
    paths: [./deploy]
portForward:
  - resourceType: service
    resourceName: portal
    port: http
    localPort: 8080
  - resourceType: service
    resourceName: api
    port: http
    localPort: 8081
profiles:
  - name: ci
    patches:
      - op: replace
        path: /build/local/push
        value: true
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: Dockerfile
