apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: devbot
build:
  artifacts:
  - image: europe-docker.pkg.dev/arikkfir/public/devbot/api
    context: ./api
    docker:
      dockerfile: Dockerfile
  - image: europe-docker.pkg.dev/arikkfir/public/devbot/portal
    context: ./portal
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: public/**
          dest: /workspace/public/
        - src: src/**
          dest: /workspace/src/
          strip: src/
  local:
    push: false
deploy:
  helm:
    releases:
      - name: local
        chartPath: ./chart
        artifactOverrides:
          api:
            image: europe-docker.pkg.dev/arikkfir/public/devbot/api
          portal:
            image: europe-docker.pkg.dev/arikkfir/public/devbot/portal
        imageStrategy:
          helm: {}
        valuesFiles:
          - values-dev.yaml
portForward:
  - resourceType: service
    namespace: default
    resourceName: devbot-local-portal
    port: http
    localPort: 8080
  - resourceType: service
    namespace: default
    resourceName: devbot-local-api
    port: http
    localPort: 8081
profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.dev
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: Dockerfile.dev
  - name: push
    patches:
      - op: replace
        path: /build/local/push
        value: true
