# nonk8s
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: devbot
build:
  artifacts:
    - image: ghcr.io/arikkfir/devbot/application-controller
      context: backend
      docker:
        dockerfile: Dockerfile.application-controller
    - image: ghcr.io/arikkfir/devbot/deployment-controller
      context: backend
      docker:
        dockerfile: Dockerfile.deployment-controller
    - image: ghcr.io/arikkfir/devbot/environment-controller
      context: backend
      docker:
        dockerfile: Dockerfile.environment-controller
    - image: ghcr.io/arikkfir/devbot/github-webhook
      context: backend
      docker:
        dockerfile: Dockerfile.github-webhook
    - image: ghcr.io/arikkfir/devbot/repository-controller
      context: backend
      docker:
        dockerfile: Dockerfile.repository-controller
  local:
    push: false
    useBuildkit: true
    concurrency: 0
manifests:
  kustomize:
    paths:
      - deploy/local
deploy:
  kubectl:
    defaultNamespace: devbot
  kubeContext: kind-devbot
portForward:
  - resourceType: service
    resourceName: devbot-github-webhook
    namespace: devbot
    port: 80
    localPort: 8080
