# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: devbot
build:
  artifacts:
    - image: ghcr.io/arikkfir/devbot/apply-job
      context: backend
      docker:
        dockerfile: Dockerfile.apply-job
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
    - image: ghcr.io/arikkfir/devbot/bake-job
      context: backend
      docker:
        dockerfile: Dockerfile.bake-job
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
    - image: ghcr.io/arikkfir/devbot/clone-job
      context: backend
      docker:
        dockerfile: Dockerfile.clone-job
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
    - image: ghcr.io/arikkfir/devbot/controller
      context: backend
      docker:
        dockerfile: Dockerfile.controller
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
      requires:
        - image: ghcr.io/arikkfir/devbot/apply-job
          alias: APPLY_JOB
        - image: ghcr.io/arikkfir/devbot/bake-job
          alias: BAKE_JOB
        - image: ghcr.io/arikkfir/devbot/clone-job
          alias: CLONE_JOB
    - image: ghcr.io/arikkfir/devbot/github-webhook
      context: backend
      docker:
        dockerfile: Dockerfile.github-webhook
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
  local:
    push: false
    useBuildkit: true
    concurrency: 0
manifests:
  kustomize:
    paths:
      - deploy/local
deploy:
  kubectl:
    defaultNamespace: devbot
  kubeContext: kind-devbot
portForward:
  - resourceType: service
    resourceName: devbot-github-webhook
    namespace: devbot
    port: 80
    localPort: 8080
