# nonk8s
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: devbot
build:
  artifacts:
    - image: ghcr.io/arikkfir/devbot/applications-controller
      context: backend
      docker:
        dockerfile: Dockerfile.applications-controller
    - image: ghcr.io/arikkfir/devbot/github-controller
      context: backend
      docker:
        dockerfile: Dockerfile.github-controller
    - image: ghcr.io/arikkfir/devbot/github-webhook
      context: backend
      docker:
        dockerfile: Dockerfile.github-webhook
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - deploy/local
deploy:
  kubeContext: kind-devbot
portForward:
  - resourceType: service
    resourceName: devbot-redis
    namespace: devbot
    port: 6379
    localPort: 6379
  - resourceType: service
    resourceName: devbot-github-webhook
    namespace: devbot
    port: 80
    localPort: 8080
