# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: devbot
build:
  artifacts:
    - image: ghcr.io/arikkfir/devbot/apply-job
      docker:
        dockerfile: build/Dockerfile.apply-job
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
    - image: ghcr.io/arikkfir/devbot/bake-job
      docker:
        dockerfile: build/Dockerfile.bake-job
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
    - image: ghcr.io/arikkfir/devbot/clone-job
      docker:
        dockerfile: build/Dockerfile.clone-job
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
    - image: ghcr.io/arikkfir/devbot/controller
      docker:
        dockerfile: build/Dockerfile.controller
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
      requires:
        - image: ghcr.io/arikkfir/devbot/apply-job
          alias: APPLY_JOB
        - image: ghcr.io/arikkfir/devbot/bake-job
          alias: BAKE_JOB
        - image: ghcr.io/arikkfir/devbot/clone-job
          alias: CLONE_JOB
    - image: ghcr.io/arikkfir/devbot/webhooks
      docker:
        dockerfile: build/Dockerfile.webhooks
        buildArgs:
          CUSTOM_GO_GCFLAGS: "all=-N -l"
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
  local:
    push: false
    useBuildkit: true
    concurrency: 0
manifests:
  kustomize:
    paths:
      - deploy/local
deploy:
  helm:
    releases:
      - name: local
        chartPath: ./deploy/chart
        namespace: devbot
        createNamespace: true
        wait: true
        setValueTemplates:
          controller.image.repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_devbot_controller}}"
          controller.image.tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_devbot_controller}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_devbot_controller}}"
          webhooks.image.repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_devbot_webhooks}}"
          webhooks.image.tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_devbot_webhooks}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_devbot_webhooks}}"
          controller.image.pullPolicy: Never # These images are only present locally, not remotely
          controller.extraEnv:
            - name: DISABLE_JSON_LOGGING
              value: "T"
            - name: LOG_LEVEL
              value: "trace"
          webhooks.image.pullPolicy: Never # These images are only present locally, not remotely
          webhooks.extraEnv:
            - name: DISABLE_JSON_LOGGING
              value: "T"
            - name: LOG_LEVEL
              value: "trace"
  kubeContext: kind-devbot
portForward:
  - resourceType: service
    resourceName: local-devbot-webhooks
    namespace: devbot
    port: 80
    localPort: 8080
