package v1

const (
	ApplyFailed                    = "ApplyFailed"
	Applying                       = "Applying"
	AuthSecretForbidden            = "AuthSecretForbidden"
	AuthSecretKeyNotFound          = "AuthSecretKeyNotFound"
	AuthSecretNotFound             = "AuthSecretNotFound"
	AuthTokenEmpty                 = "AuthTokenEmpty"
	Authenticated                  = "Authenticated"
	AuthenticationFailed           = "AuthenticationFailed"
	Baking                         = "Baking"
	BakingFailed                   = "BakingFailed"
	BranchNotFound                 = "BranchNotFound"
	CloneFailed                    = "CloneFailed"
	Cloning                        = "Cloning"
	Current                        = "Current"
	DeploymentsAreStale            = "DeploymentsAreStale"
	EnvironmentsAreStale           = "EnvironmentsAreStale"
	FailedCreatingDeployment       = "FailedCreatingDeployment"
	FailedDeletingDeployment       = "FailedDeletingDeployment"
	FailedToInitialize             = "FailedToInitialize"
	Finalized                      = "Finalized"
	Finalizing                     = "Finalizing"
	Initialized                    = "Initialized"
	Invalid                        = "Invalid"
	InvalidBranchSpecification     = "InvalidBranchSpecification"
	InvalidRefreshInterval         = "InvalidRefreshInterval"
	PersistentVolumeCreationFailed = "PersistentVolumeCreationFailed"
	PersistentVolumeMissing        = "PersistentVolumeMissing"
	RepositoryNotAccessible        = "RepositoryNotAccessible"
	RepositoryNotFound             = "RepositoryNotFound"
	RepositoryNotSupported         = "RepositoryNotSupported"
	Stale                          = "Stale"
	Unauthenticated                = "Unauthenticated"
	UnknownRepositoryType          = "UnknownRepositoryType"
	Valid                          = "Valid"
	WebhookSecretEmpty             = "WebhookSecretEmpty"
	WebhookSecretForbidden         = "WebhookSecretForbidden"
	WebhookSecretKeyMissing        = "WebhookSecretKeyMissing"
	WebhookSecretKeyNotFound       = "WebhookSecretKeyNotFound"
	WebhookSecretNameMissing       = "WebhookSecretNameMissing"
	WebhookSecretNotFound          = "WebhookSecretNotFound"
	WebhooksNotEnabled             = "WebhooksNotEnabled"
)
