# syntax=docker/dockerfile:1

FROM golang:1.21 as builder
ARG TARGETOS
# no default value, to default to the environment's architecture (e.g. linux/amd64)
ARG TARGETARCH
ARG SKAFFOLD_GO_GCFLAGS="all=-N -l"

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN --mount=type=cache,target=/go/pkg go mod download

COPY api api/
COPY cmd/github-repository-ref-controller cmd/github-repository-ref-controller/
COPY internal/config/base.go internal/config/
COPY internal/controllers/config.go internal/controllers/
COPY internal/controllers/repositories/github/github_repository_ref_controller.go internal/controllers/repositories/github/
COPY internal/util/configuration/parse.go internal/util/configuration/
COPY internal/util/logging/initialization.go internal/util/logging/
COPY internal/util/logging/zerolog_logr_adapter.go internal/util/logging/
COPY internal/util/k8s/debug.go internal/util/k8s/
COPY internal/util/k8s/ownership.go internal/util/k8s/
COPY internal/util/strings/hash.go internal/util/strings/
RUN --mount=type=cache,target=/go/pkg CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -a -o github-repository-ref-controller cmd/github-repository-ref-controller/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/github-repository-ref-controller ./
USER 65532:65532
ENV GOTRACEBACK=single
ENTRYPOINT ["/github-repository-ref-controller"]
