# syntax=docker/dockerfile:1

FROM golang:1.21 as builder
ARG TARGETOS
# no default value, to default to the environment's architecture (e.g. linux/amd64)
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY api api/
COPY cmd/applications-controller cmd/applications-controller/
COPY internal/config internal/config/
COPY internal/util internal/util/
COPY internal/controllers/applications_controller.go internal/controllers/applications_controller.go
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o applications-controller cmd/applications-controller/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/applications-controller ./
USER 65532:65532
ENTRYPOINT ["/applications-controller"]
