# syntax=docker/dockerfile:1

FROM golang:1.21 as builder
ARG TARGETOS
# no default value, to default to the environment's architecture (e.g. linux/amd64)
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY api api/
COPY cmd/application-commit-handler cmd/application-commit-handler/
COPY internal/config internal/config/
COPY internal/util internal/util/
COPY internal/webhooks internal/webhooks/
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o application-commit-handler cmd/application-commit-handler/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/application-commit-handler ./
USER 65532:65532
ENTRYPOINT ["/application-commit-handler"]
