# syntax=docker/dockerfile:1

FROM golang:1.22 as builder
ARG TARGETOS
# no default value, to default to the environment's architecture (e.g. linux/amd64)
ARG TARGETARCH
ARG SKAFFOLD_GO_GCFLAGS="all=-N -l"

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN --mount=type=cache,target=/go/pkg go mod download

COPY api api/
COPY cmd/application-controller/main.go cmd/application-controller/
COPY internal/config/base.go internal/config/
COPY internal/controllers/config.go internal/controllers/
COPY internal/controllers/application/controller.go internal/controllers/application/
COPY internal/util/configuration/parse.go internal/util/configuration/
COPY internal/util/k8s/conditions.go internal/util/k8s/
COPY internal/util/k8s/owned_by.go internal/util/k8s/
COPY internal/util/k8s/reconciliation.go internal/util/k8s/
COPY internal/util/k8s/result.go internal/util/k8s/
COPY internal/util/k8s/status.go internal/util/k8s/
COPY internal/util/lang/duration.go internal/util/lang/
COPY internal/util/lang/pointers.go internal/util/lang/
COPY internal/util/logging/initialization.go internal/util/logging/
COPY internal/util/logging/zerolog_logr_adapter.go internal/util/logging/
COPY internal/util/strings/buffer_async_lines_extractor.go internal/util/strings/
COPY internal/util/strings/hash.go internal/util/strings/
COPY internal/util/strings/names.go internal/util/strings/
COPY internal/util/strings/slug.go internal/util/strings/
RUN --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build \
      -gcflags="${SKAFFOLD_GO_GCFLAGS}" \
      -a -o application-controller \
      cmd/application-controller/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/application-controller /usr/local/bin/
USER 65532:65532
ENV GOTRACEBACK=single
ENTRYPOINT ["/usr/local/bin/application-controller"]
