apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  selector:
    matchLabels: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      containers:
        - args: []
          env:
            - name: PORT
              value: "8000"
          image: nginx
          name: portal
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: my-app
