name: Setup Runner
description: Setup the runner for devbot workflows.
inputs:
  gcp-project-id:
    required: true
    description: GCP alphanumeric project ID.
  gcp-service-account-key:
    required: true
    description: GCP service account JSON key.
runs:
  using: composite
  steps:
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ inputs.gcp-project-id }}
        service_account_key: ${{ inputs.gcp-service-account-key }}
        export_default_credentials: true
        credentials_file_path: gcloud_google_credentials
    - name: Authenticate to Google Artifact Registry
      run: gcloud auth configure-docker europe-docker.pkg.dev
      shell: bash -eu {0}
    - name: Setup Kind
      uses: helm/kind-action@v1.2.0
      with:
        cluster_name: testing
    - name: Setup Skaffold
      run: curl -sSL -o /usr/local/bin/skaffold "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64" && chmod +x /usr/local/bin/skaffold
      shell: bash -eu {0}
