resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  type: pvc
  enabled: true
  size: 10Gi

env:
  GF_DEFAULT_INSTANCE_NAME: grafana
  GF_SERVER_ENABLE_GZIP: "true"
  GF_USERS_DEFAULT_THEME: "system"

adminUser: admin
adminPassword: devbot

datasources:
  datasources.yaml:
    apiVersion: 1
    prune: true
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observability.svc.cluster.local
        access: proxy
        isDefault: true
        editable: false
    deleteDatasources:
      - name: Prometheus

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: grafana-dashboards

#grafana.ini:
#  paths:
#    data: /var/lib/grafana/
#    logs: /var/log/grafana
#    plugins: /var/lib/grafana/plugins
#    provisioning: /etc/grafana/provisioning
#  analytics:
#    check_for_updates: true
#  log:
#    mode: console
#  grafana_net:
#    url: https://grafana.net
#  server:
#    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"
      ## grafana Authentication can be enabled with the following values on grafana.ini
      # server:
    # The full public facing url you use in browser, used for redirects and emails
  #    root_url:
  # https://grafana.com/docs/grafana/latest/auth/github/#enable-github-in-grafana
  # auth.github:
  #    enabled: false
  #    allow_sign_up: false
  #    scopes: user:email,read:org
  #    auth_url: https://github.com/login/oauth/authorize
  #    token_url: https://github.com/login/oauth/access_token
  #    api_url: https://api.github.com/user
  #    team_ids:
  #    allowed_organizations:
  #    client_id:
  #    client_secret:
