global:
  # Set the verbosity of cert-manager. A range of 0 - 6, with 6 being the most verbose.
  logLevel: 2
  leaderElection:
    namespace: "kube-system"

crds:
  enabled: true
  keep: false

enableCertificateOwnerRef: true

resources:
  requests:
    cpu: 100m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

prometheus:
  enabled: true
  podmonitor:
    enabled: false
    prometheusInstance: default
