apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  # TODO: add HPA
  - patch: |-
      - op: set
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 0
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--log-json"
      - op: add
        path: /spec/template/metadata/annotations/-
        value:
          prometheus.io/path: /metrics
          prometheus.io/port: "9001"
          prometheus.io/scrape: "true"
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/name=devbot
