apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applications-controller
rules:
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - applications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - applications/finalizers
    verbs:
      - update
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - applications/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: applications-controller@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: applications-controller
  name: applications-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: applications-controller
  name: applications-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: applications-controller
subjects:
  - kind: ServiceAccount
    name: applications-controller
    namespace: devbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: applications-controller
  name: applications-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: applications-controller
    namespace: devbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: applications-controller
  name: applications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: applications-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: applications-controller
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/applications-controller
          args: []
          name: applications-controller
          ports:
            - containerPort: 8000
              name: metrics
            - containerPort: 9000
              name: health
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: applications-controller
