apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-controller
rules:
  - apiGroups: [devbot.kfirs.com]
    resources: [applications]
    verbs: [get, list, patch, update, watch]
  - apiGroups: [devbot.kfirs.com]
    resources: [applications/status]
    verbs: [create, delete, get, patch, update]
  - apiGroups: [devbot.kfirs.com]
    resources: [environments]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [devbot.kfirs.com]
    resources: [repositories]
    verbs: [get, list, watch]
  - apiGroups: [devbot.kfirs.com]
    resources: [repositories/status]
    verbs: [get]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: application-controller@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: application-controller
  name: application-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
  name: application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-controller
subjects:
  - kind: ServiceAccount
    name: application-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
  name: application-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: application-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/component-type: controller
    app.kubernetes.io/std-logger: "true"
  name: application-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: application-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: application-controller
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/application-controller
          args: []
          name: application-controller
          ports:
            - containerPort: 8000
              name: metrics
            - containerPort: 9000
              name: health
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: application-controller
