apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: application-commit-handler
  name: application-commit-handler
rules:
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - applications/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: application-commit-handler@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: application-commit-handler
  name: application-commit-handler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-commit-handler
  name: application-commit-handler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-commit-handler
subjects:
  - kind: ServiceAccount
    name: application-commit-handler
    namespace: devbot
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: application-commit-handler
  name: application-commit-handler
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: application-commit-handler
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: application-commit-handler
  name: application-commit-handler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: application-commit-handler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: application-commit-handler
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/application-commit-handler
          env:
            - name: REDIS_HOST
              value: devbot-redis
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: WEBHOOK_SECRET
                  name: webhooks
                  optional: false
          name: application-commit-handler
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: health
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: application-commit-handler
