apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployments-controller
rules:
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - devbot.kfirs.com
    resources:
      - deployments/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: deployments-controller@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: deployments-controller
  name: deployments-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: deployments-controller
  name: deployments-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployments-controller
subjects:
  - kind: ServiceAccount
    name: deployments-controller
    namespace: devbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: deployments-controller
  name: deployments-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: deployments-controller
    namespace: devbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: deployments-controller
  name: deployments-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: deployments-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: deployments-controller
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/deployments-controller
          args: []
          name: deployments-controller
          ports:
            - containerPort: 8000
              name: metrics
            - containerPort: 9000
              name: health
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: deployments-controller
