apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-environment-controller
rules:
  - apiGroups: [devbot.kfirs.com]
    resources: [applications, applications/status]
    verbs: [get, list, watch]
  - apiGroups: [devbot.kfirs.com]
    resources: [applicationenvironments, applicationenvironments/status]
    verbs: [create, get, list, watch, patch, update, delete]
  - apiGroups: [devbot.kfirs.com]
    resources: [deployments, deployments/status]
    verbs: [create, get, list, watch, patch, update, delete]
  - apiGroups: [devbot.kfirs.com]
    resources: [githubrepositories, githubrepositoryrefs/status, githubrepositoryrefs, githubrepositoryrefs/status]
    verbs: [get, list, watch]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: application-environment-controller@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: application-environment-controller
  name: application-environment-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-environment-controller
  name: application-environment-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-environment-controller
subjects:
  - kind: ServiceAccount
    name: application-environment-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-environment-controller
  name: application-environment-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: application-environment-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: application-environment-controller
    app.kubernetes.io/component-type: controller
    app.kubernetes.io/std-logger: "true"
  name: application-environment-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: application-environment-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: application-environment-controller
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/application-environment-controller
          args: []
          env:
            - name: REDIS_HOST
              value: devbot-redis
          name: application-environment-controller
          ports:
            - containerPort: 8000
              name: metrics
            - containerPort: 9000
              name: health
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: application-environment-controller
