apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: devbot
namePrefix: devbot-
namespace: devbot
resources:
  - crd/devbot.kfirs.com_applicationenvironments.yaml
  - crd/devbot.kfirs.com_applications.yaml
  - crd/devbot.kfirs.com_deployments.yaml
  - crd/devbot.kfirs.com_githubrepositories.yaml
  - crd/devbot.kfirs.com_githubrepositoryrefs.yaml
  - namespace.yaml
  - application-controller.yaml
  - application-environment-controller.yaml
  - github-repository-controller.yaml
  - github-repository-ref-controller.yaml
  - github-webhook.yaml
  - leader-election.yaml
  - redis.yaml
