apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: github-webhook
  name: github-webhook
rules:
  - apiGroups: [devbot.kfirs.com]
    resources: [repositories]
    verbs: [get, list, patch, update, watch]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: github-webhook@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: github-webhook
  name: github-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: github-webhook
  name: github-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-webhook
subjects:
  - kind: ServiceAccount
    name: github-webhook
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: github-webhook
  name: github-webhook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: github-webhook
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: github-webhook
    app.kubernetes.io/component-type: webhook
    app.kubernetes.io/std-logger: "true"
  name: github-webhook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: github-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: github-webhook
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/github-webhook
          name: github-webhook
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: health
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
      enableServiceLinks: false
      serviceAccountName: github-webhook
