apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-auth-access.yaml
secretGenerator:
  - type: Opaque
    behavior: create
    name: devbot-github-auth
    namespace: devbot
    options:
      disableNameSuffixHash: true
      immutable: true
    envs:
      - github-auth.env
