apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--log-caller-info"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--http-log-response-body"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "1"
            memory: 500Mi
          limits:
            cpu: "1"
            memory: 500Mi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: portal
