apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devbot
    app.kubernetes.io/component: api
  name: api
spec:
  selector:
    app.kubernetes.io/name: devbot
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: metrics
    - name: health
      protocol: TCP
      port: 9001
      targetPort: health
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devbot
    app.kubernetes.io/component: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devbot
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devbot
        app.kubernetes.io/component: api
    spec:
      containers:
        - args:
            - --http-address=:8080
            - --log-caller-info
            - --http-log-response-body
          image: europe-docker.pkg.dev/arikkfir/public/devbot/api
          name: api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9000
              name: metrics
              protocol: TCP
            - containerPort: 9001
              name: health
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 100Mi
