apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: applications-controller@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: applications-controller
  name: applications-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: applications-controller
  name: applications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: applications-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: applications-controller
    spec:
      containers:
        - image: ghcr.io/arikkfir/devbot/applications-controller
          name: server
          livenessProbe:
            httpGet:
              port: health
              path: /healthz
            failureThreshold: 3
            periodSeconds: 5
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: health
          readinessProbe:
            httpGet:
              port: health
              path: /readyz
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
          startupProbe:
            httpGet:
              port: health
              path: /healthz
            failureThreshold: 5
            periodSeconds: 1
            timeoutSeconds: 1
      enableServiceLinks: false
      serviceAccountName: applications-controller
