---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applications-controller
rules:
- apiGroups:
  - devbot.kfirs.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devbot.kfirs.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - devbot.kfirs.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
