apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: "${ENVIRONMENT}-"
labels:
  - pairs:
      app.kubernetes.io/name: "${APPLICATION}"
      app.kubernetes.io/instance: "${ENVIRONMENT}"
      app.kubernetes.io/component: common
      app.kubernetes.io/version: "${COMMIT_SHA}"
    fields:
      - path: metadata/labels
        create: true
resources:
  - configmap.yaml
