apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
generatorOptions:
  disableNameSuffixHash: true
  immutable: true
secretGenerator:
  - name: otel-collector-gcp
    type: Opaque
    files:
      - service-account-key.json
