//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithCommonConditions) DeepCopyInto(out *ObjectWithCommonConditions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithCommonConditions.
func (in *ObjectWithCommonConditions) DeepCopy() *ObjectWithCommonConditions {
	if in == nil {
		return nil
	}
	out := new(ObjectWithCommonConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectWithCommonConditions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithCommonConditionsList) DeepCopyInto(out *ObjectWithCommonConditionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectWithCommonConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithCommonConditionsList.
func (in *ObjectWithCommonConditionsList) DeepCopy() *ObjectWithCommonConditionsList {
	if in == nil {
		return nil
	}
	out := new(ObjectWithCommonConditionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectWithCommonConditionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithCommonConditionsSpec) DeepCopyInto(out *ObjectWithCommonConditionsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithCommonConditionsSpec.
func (in *ObjectWithCommonConditionsSpec) DeepCopy() *ObjectWithCommonConditionsSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectWithCommonConditionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithCommonConditionsStatus) DeepCopyInto(out *ObjectWithCommonConditionsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithCommonConditionsStatus.
func (in *ObjectWithCommonConditionsStatus) DeepCopy() *ObjectWithCommonConditionsStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectWithCommonConditionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithoutCommonConditions) DeepCopyInto(out *ObjectWithoutCommonConditions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithoutCommonConditions.
func (in *ObjectWithoutCommonConditions) DeepCopy() *ObjectWithoutCommonConditions {
	if in == nil {
		return nil
	}
	out := new(ObjectWithoutCommonConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectWithoutCommonConditions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithoutCommonConditionsList) DeepCopyInto(out *ObjectWithoutCommonConditionsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectWithoutCommonConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithoutCommonConditionsList.
func (in *ObjectWithoutCommonConditionsList) DeepCopy() *ObjectWithoutCommonConditionsList {
	if in == nil {
		return nil
	}
	out := new(ObjectWithoutCommonConditionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectWithoutCommonConditionsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithoutCommonConditionsSpec) DeepCopyInto(out *ObjectWithoutCommonConditionsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithoutCommonConditionsSpec.
func (in *ObjectWithoutCommonConditionsSpec) DeepCopy() *ObjectWithoutCommonConditionsSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectWithoutCommonConditionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectWithoutCommonConditionsStatus) DeepCopyInto(out *ObjectWithoutCommonConditionsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectWithoutCommonConditionsStatus.
func (in *ObjectWithoutCommonConditionsStatus) DeepCopy() *ObjectWithoutCommonConditionsStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectWithoutCommonConditionsStatus)
	in.DeepCopyInto(out)
	return out
}
