package v1

const (
	AddFinalizerFailed             = "AddFinalizerFailed"
	ApplyFailed                    = "ApplyFailed"
	AuthConfigMissing              = "AuthConfigMissing"
	AuthSecretForbidden            = "AuthSecretForbidden"
	AuthSecretGetFailed            = "AuthSecretGetFailed"
	AuthSecretKeyMissing           = "AuthSecretKeyMissing"
	AuthSecretKeyNotFound          = "AuthSecretKeyNotFound"
	AuthSecretNameMissing          = "AuthSecretNameMissing"
	AuthSecretNotFound             = "AuthSecretNotFound"
	AuthTokenEmpty                 = "AuthTokenEmpty"
	BakingFailed                   = "BakingFailed"
	BranchesOutOfSync              = "BranchesOutOfSync"
	CloneFailed                    = "CloneFailed"
	CloneMissing                   = "CloneMissing"
	Cloning                        = "Cloning"
	CommitSHAOutOfSync             = "CommitSHAOutOfSync"
	ControllerMissing              = "ControllerMissing"
	DefaultBranchOutOfSync         = "DefaultBranchOutOfSync"
	DeploymentNotFound             = "DeploymentNotFound"
	FailedGettingOwnedObjects      = "FailedGettingOwnedObjects"
	FinalizationFailed             = "FinalizationFailed"
	GitHubAPIFailed                = "GitHubAPIFailed"
	InternalError                  = "InternalError"
	Invalid                        = "Invalid"
	InvalidRefreshInterval         = "InvalidRefreshInterval"
	RepositoryAdded                = "RepositoryAdded"
	RepositoryMissingDefaultBranch = "RepositoryMissingDefaultBranch"
	RepositoryNameMissing          = "RepositoryNameMissing"
	RepositoryNameOutOfSync        = "RepositoryNameOutOfSync"
	RepositoryNotAccessible        = "RepositoryNotAccessible"
	RepositoryNotApplicable        = "RepositoryNotApplicable"
	RepositoryNotFound             = "RepositoryNotFound"
	RepositoryNotSupported         = "RepositoryNotSupported"
	RepositoryOwnerMissing         = "RepositoryOwnerMissing"
	RepositoryOwnerOutOfSync       = "RepositoryOwnerOutOfSync"
	Stale                          = "Stale"
	TokenValidationFailed          = "TokenValidationFailed"
	Unauthenticated                = "Unauthenticated"
)
