package v1

const (
	ApplyFailed                    = "ApplyFailed"
	Applying                       = "Applying"
	AuthConfigMissing              = "AuthConfigMissing"
	AuthSecretForbidden            = "AuthSecretForbidden"
	AuthSecretKeyMissing           = "AuthSecretKeyMissing"
	AuthSecretKeyNotFound          = "AuthSecretKeyNotFound"
	AuthSecretNameMissing          = "AuthSecretNameMissing"
	AuthSecretNotFound             = "AuthSecretNotFound"
	AuthTokenEmpty                 = "AuthTokenEmpty"
	Authenticated                  = "Authenticated"
	AuthenticationFailed           = "AuthenticationFailed"
	Baking                         = "Baking"
	BakingFailed                   = "BakingFailed"
	BranchNotFound                 = "BranchNotFound"
	BranchesOutOfSync              = "BranchesOutOfSync"
	CloneFailed                    = "CloneFailed"
	Cloning                        = "Cloning"
	Current                        = "Current"
	DefaultBranchOutOfSync         = "DefaultBranchOutOfSync"
	DeploymentsAreStale            = "DeploymentsAreStale"
	EnvironmentsAreStale           = "EnvironmentsAreStale"
	FailedCreatingDeployment       = "FailedCreatingDeployment"
	FailedDeletingDeployment       = "FailedDeletingDeployment"
	FailedToInitialize             = "FailedToInitialize"
	Finalized                      = "Finalized"
	Finalizing                     = "Finalizing"
	Initialized                    = "Initialized"
	Invalid                        = "Invalid"
	InvalidBranchSpecification     = "InvalidBranchSpecification"
	InvalidRefreshInterval         = "InvalidRefreshInterval"
	PersistentVolumeCreationFailed = "PersistentVolumeCreationFailed"
	PersistentVolumeMissing        = "PersistentVolumeMissing"
	RepositoryNameMissing          = "RepositoryNameMissing"
	RepositoryNotAccessible        = "RepositoryNotAccessible"
	RepositoryNotFound             = "RepositoryNotFound"
	RepositoryNotSupported         = "RepositoryNotSupported"
	RepositoryOwnerMissing         = "RepositoryOwnerMissing"
	Stale                          = "Stale"
	Unauthenticated                = "Unauthenticated"
	UnknownRepositoryType          = "UnknownRepositoryType"
	Valid                          = "Valid"
)
