package v1

const (
	ApplyFailed                = "ApplyFailed"
	Applying                   = "Applying"
	AuthConfigMissing          = "AuthConfigMissing"
	AuthSecretForbidden        = "AuthSecretForbidden"
	AuthSecretKeyMissing       = "AuthSecretKeyMissing"
	AuthSecretKeyNotFound      = "AuthSecretKeyNotFound"
	AuthSecretNameMissing      = "AuthSecretNameMissing"
	AuthSecretNotFound         = "AuthSecretNotFound"
	AuthTokenEmpty             = "AuthTokenEmpty"
	AuthenticationFailed       = "AuthenticationFailed"
	Baking                     = "Baking"
	BakingFailed               = "BakingFailed"
	BranchNotFound             = "BranchNotFound"
	BranchesOutOfSync          = "BranchesOutOfSync"
	CheckoutFailed             = "CheckoutFailed"
	CloneFailed                = "CloneFailed"
	CloneMissing               = "CloneMissing"
	CloneOpenFailed            = "CloneOpenFailed"
	Cloning                    = "Cloning"
	ControllerNotAccessible    = "ControllerNotAccessible"
	ControllerNotFound         = "ControllerNotFound"
	ControllerReferenceMissing = "ControllerReferenceMissing"
	DefaultBranchOutOfSync     = "DefaultBranchOutOfSync"
	DeploymentsAreStale        = "DeploymentsAreStale"
	EnvironmentsAreStale       = "EnvironmentsAreStale"
	FailedCreatingDeployment   = "FailedCreatingDeployment"
	FailedDeletingDeployment   = "FailedDeletingDeployment"
	FailedToInitialize         = "FailedToInitialize"
	FetchFailed                = "FetchFailed"
	FinalizationFailed         = "FinalizationFailed"
	FinalizerRemovalFailed     = "FinalizerRemovalFailed"
	Finalizing                 = "Finalizing"
	InProgress                 = "InProgress"
	InternalError              = "InternalError"
	Invalid                    = "Invalid"
	InvalidRefreshInterval     = "InvalidRefreshInterval"
	RepositoryNameMissing      = "RepositoryNameMissing"
	RepositoryNotAccessible    = "RepositoryNotAccessible"
	RepositoryNotFound         = "RepositoryNotFound"
	RepositoryNotSupported     = "RepositoryNotSupported"
	RepositoryOwnerMissing     = "RepositoryOwnerMissing"
	Stale                      = "Stale"
	Unauthenticated            = "Unauthenticated"
	UnknownRepositoryType      = "UnknownRepositoryType"
)
