apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/branch: main
    app.kubernetes.io/instance: my-feature
    app.kubernetes.io/name: myapp
    app.kubernetes.io/version: abc123
  name: test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
        - command:
            - sleep
            - "60"
          image: busybox
          name: test
      serviceAccountName: test-sa
