### Build webhooks executable
FROM golang:1.17 as builder
WORKDIR /workspace

# Copy the Go manifests, download dependencies & cache them before building and copying actual source code, so when
# source code changes, downloaded dependencies stay cached and are not downloaded again (unless manifest changes too.)
COPY go.mod go.sum ./
RUN go mod download

# Now build the actual executable
COPY main.go ./
COPY internal ./internal
ENV CGO_ENABLED="0"
ENV GOARCH="amd64"
ENV GOOS="linux"
ENV GO111MODULE="on"
ARG SKAFFOLD_GO_GCFLAGS
RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o bin/api main.go

ENV GOTRACEBACK=all
ENTRYPOINT ["bin/api"]
