name: Build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:

  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: [ apply-job, bake-job, clone-job, controller, github-webhook ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/arikkfir/devbot/${{ matrix.image }}
          tags: |
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=v{{version}}
            type=sha,format=long            
            type=sha,format=short
      - uses: docker/build-push-action@v5
        with:
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            VERSION=0.0.0+${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: backend
          file: backend/Dockerfile.${{ matrix.image }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
