name: CI
on:
  push:
    branches: ["*"]
  workflow_dispatch:
defaults:
  run:
    shell: bash -eu {0}
jobs:
  verify:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: arikkfir/infrastructure/.github/actions/setup-gcloud@main
        with:
          service_account: devbot-github-actions@arikkfir.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup Tools
        uses: arikkfir/infrastructure/.github/actions/setup-tools@main
        with:
          docker: "true"
          helm: "true"
          skaffold: "true"
          yq: "true"
      - name: Build Docker images
        run: skaffold build --tag=${GITHUB_SHA::7} --file-output=skaffold-tags.json --profile=push
      - name: Package Helm Chart
        id: package-helm-chart
        uses: arikkfir/infrastructure/.github/actions/package-helm-chart@main
        with:
          directory: chart
      - name: Prepare environment
        id: prepare-environment
        uses: arikkfir/infrastructure/.github/actions/prepare-deployment-environment@main
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.PAT }}
      - name: Patch Infrastructure
        run: |-
          yq --prettyPrint eval --inplace '
            ((.[] | {.path:.}) as $i ireduce ({}; . * $i)) * 
              {
                "/spec/chart/spec/version": {"op": "replace", "path": "/spec/chart/spec/version", "value": "${{ steps.package-helm-chart.outputs.version }}"},
                "/spec/values/ingress/dns/record/name": {"op": "replace", "path": "/spec/values/ingress/dns/record/name", "value": "devbot.${{ github.ref_name }}.kfirs.com"}
              } 
            | to_entries | [.[].value]' \
            patch-devbot-helmrelease.yaml
        working-directory: ${{ steps.prepare-environment.outputs.environment-directory }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          branch_mode: create
          cwd: ".deploy_infra" #${{ steps.prepare-environment.outputs.environment-directory }}
          author_name: github-actions
          author_email: <github-actions@users.noreply.github.com>
          message: Deploy "devbot-${{ steps.package-helm-chart.outputs.version }}" in "${{ github.ref_name }}"
