name: Validation

on:
  push:
    branches: [main]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:

  validate-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make setup
      - uses: golangci/golangci-lint-action@v6
        with:
          args: --out-format=github-actions:stderr
          version: latest
      - run: make generate
      - run: make e2e-unfocus
      - run: git status
      - run: git diff-index HEAD --exit-code --color --summary
