name: Validation

on:
  push:
    branches: [main]
    tags:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:

  validate-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod download -x
      - uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=30m
          version: latest
