name: Verify
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/verify.yml
      - api/**
      - deploy/**
      - portal/**
      - go.*
      - skaffold.yaml
  workflow_dispatch:
defaults:
  run:
    shell: sh -eu {0}
jobs:
  verify:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      SKAFFOLD_DOWNLOAD_URL: https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
#      KUBECTL_DOWNLOAD_URL: https://dl.k8s.io/release/v1.22.3/bin/linux/amd64/kubectl
#      CONTAINER_STRUCTURE_TEST_DOWNLOAD_URL: https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - run: gcloud info
      - uses: hiberbee/github-action-minikube@1.6.0
        with:
          kubernetes-version: 1.22.3
          nodes: 1
          cpus: 2
      - run: curl -sSL -o /usr/local/bin/skaffold "${SKAFFOLD_DOWNLOAD_URL}" && chmod +x /usr/local/bin/skaffold
#      - run: curl -sSL -o /usr/local/bin/container-structure-test "${CONTAINER_STRUCTURE_TEST_DOWNLOAD_URL}" && chmod +x /usr/local/bin/container-structure-test
      - run: skaffold build --file-output=build.json --profile=ci
      - run: skaffold render --build-artifacts=build.json --profile=ci --output=devbot.yaml
      - run: cat devbot.yaml
##      - run: skaffold test --build-artifacts=tags.json

#      - uses: hiberbee/github-action-skaffold@1.12.0
#        with:
#          skaffold-version: 1.34.0
#          container-structure-test-version: 1.10.0
#          command: render
#          profile: ci
