name: Verify
on:
  push:
    branches: [main]
    paths:
      - .github/actions/**
      - .github/workflows/verify.yml
      - api/**
      - deploy/**
      - portal/**
      - go.*
      - skaffold.yaml
  workflow_dispatch:
defaults:
  run:
    shell: bash -eu {0}
jobs:
  verify:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - name: Setup build container
        run: |-
          echo "::group::Setting up dependencies"
          apt-get update && apt-get install -y curl python3 docker.io
          echo "::endgroup::"
          echo "::group::Installing skaffold"
          curl -sSL -o /usr/local/bin/skaffold "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64" && chmod +x /usr/local/bin/skaffold
          echo "::endgroup::"
          echo "::group::Installing Google Cloud SDK"
          curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-367.0.0-linux-x86_64.tar.gz | tar xz -C /usr/local \
            && /usr/local/google-cloud-sdk/install.sh --quiet --additional-components kubectl kustomize \
            && pushd /usr/local/google-cloud-sdk/bin \
            && ln -s $(pwd)/bq \
                     $(pwd)/docker-credential-gcloud \
                     $(pwd)/gcloud \
                     $(pwd)/gsutil \
                     $(pwd)/kubectl \
                     $(pwd)/kustomize \
                     /usr/local/bin/ \
            && popd
          echo "::endgroup::"
        env:
            DEBIAN_FRONTEND: noninteractive
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/default
          service_account: devbot-github-actions@arikkfir.iam.gserviceaccount.com
      - name: Authenticate to Google Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker images
        run: skaffold build --file-output=skaffold-tags.json --profile=ci
      - uses: helm/kind-action@v1.2.0
      - run: docker ps -a
      - name: Deploy to local cluster
        run: skaffold deploy --build-artifacts=skaffold-tags.json --profile=ci
      - name: Test
        run: |-
          echo "::group::Setting up port-forwarding"
          kubectl port-forward service/api 8081:80 &
          kubectl port-forward service/portal 8080:80 &
          echo "Sleeping a bit..." && sleep 3
          echo "::endgroup::"
          echo "::group::Testing"
          curl -isSL http://localhost:8080
          curl -isSL http://localhost:8081
          echo "::endgroup::"
      - name: Checkout Infrastructure
        uses: actions/checkout@v2
        with:
          repository: arikkfir/infrastructure
          ref: main
          token: ${{ secrets.PAT }}
          path: infrastructure
      - name: Patch Infrastructure
        run: |-
          kustomize edit set image \
            $(cat ../../../../skaffold-tags.json | jq -r '.builds[] | select(.imageName=="europe-docker.pkg.dev/arikkfir/public/devbot/api") | .tag') \
            $(cat ../../../../skaffold-tags.json | jq -r '.builds[] | select(.imageName=="europe-docker.pkg.dev/arikkfir/public/devbot/portal") | .tag')
        working-directory: infrastructure/kubernetes/manifests/devbot
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          cwd: ./infrastructure
          author_name: github-actions
          author_email: <github-actions@users.noreply.github.com>
          message: Update Devbot Kubernetes manifest
