name: Verify
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/verify.yml
      - api/**
      - deploy/**
      - portal/**
      - go.*
      - skaffold.yaml
  workflow_dispatch:
defaults:
  run:
    shell: sh -eu {0}
jobs:
  verify:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          credentials_file_path: gcloud_google_credentials
      - name: Authenticate to Google Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Pull the API Docker image of the previous commit
        run: docker pull europe-docker.pkg.dev/arikkfir/public/devbot/api:$(git rev-parse ${{ github.sha }}^ | cut -c 1-7)
        continue-on-error: true
      - name: Pull the Portal Docker image of the previous commit
        run: docker pull europe-docker.pkg.dev/arikkfir/public/devbot/portal:$(git rev-parse ${{ github.sha }}^ | cut -c 1-7)
        continue-on-error: true
      - name: Setup Skaffold
        run: curl -sSL -o /usr/local/bin/skaffold "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64" && chmod +x /usr/local/bin/skaffold
      # TODO: deploy to Minikube & run test suite
#      - name: Setup Minikube
#        uses: hiberbee/github-action-minikube@1.6.0
#        with:
#          kubernetes-version: 1.22.3
#          nodes: 1
#          cpus: 2
      - run: git status
      - name: Build
        run: skaffold build --file-output=build.json --profile=ci
      - name: Render Kubernetes manifests
        run: skaffold render --build-artifacts=build.json --profile=ci --output=devbot.yaml
      # TODO: clone infrastructure repo, commit devbot.yaml for FluxCD to apply to cluster

