name: Verify
on:
  push:
  workflow_dispatch:
  workflow_call:
defaults:
  run:
    shell: bash -eu {0}
jobs:
  verify:
    runs-on: ubuntu-20.04
    container: ubuntu:21.10
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 15
    steps:
      - name: Setup Google Cloud SDK
        uses: arikkfir/infrastructure/.github/actions/setup-gcloud@main
        with:
          service_account: devbot-github-actions@arikkfir.iam.gserviceaccount.com
      - name: Setup Docker
        run: apt-get update && apt-get install -y docker.io
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Setup Skaffold
        uses: arikkfir/infrastructure/.github/actions/setup-skaffold@main
#      - name: Install Skaffold
#        run: curl -sSL -o /usr/local/bin/skaffold "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64" && chmod +x /usr/local/bin/skaffold
      - name: Authenticate to Google Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker images
        run: skaffold build --file-output=skaffold-tags.json --profile=ci
#      - name: Checkout Infrastructure
#        uses: actions/checkout@v2
#        with:
#          repository: arikkfir/infrastructure
#          ref: main
#          token: ${{ secrets.PAT }}
#          path: infrastructure
#      - name: Patch Infrastructure
#        run: |-
#          kustomize edit set image \
#            $(cat ../../../../skaffold-tags.json | jq -r '.builds[] | select(.imageName=="europe-docker.pkg.dev/arikkfir/public/devbot/api") | .tag') \
#            $(cat ../../../../skaffold-tags.json | jq -r '.builds[] | select(.imageName=="europe-docker.pkg.dev/arikkfir/public/devbot/portal") | .tag')
#        working-directory: infrastructure/kubernetes/manifests/devbot
#      - name: Commit changes
#        uses: EndBug/add-and-commit@v7
#        with:
#          cwd: ./infrastructure
#          author_name: github-actions
#          author_email: <github-actions@users.noreply.github.com>
#          message: Update Devbot Kubernetes manifest
