name: Verify
on:
  push:
    branches: [main]
    paths:
      - .github/actions/**
      - .github/workflows/verify.yml
      - api/**
      - deploy/**
      - portal/**
      - go.*
      - skaffold.yaml
  workflow_dispatch:
defaults:
  run:
    shell: bash -eu {0}
jobs:
  verify:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Runner
        uses: ./.github/actions/setup-runner
        with:
          gcp-project-id: ${{ secrets.GCP_PROJECT_ID }}
          gcp-service-account-key: ${{ secrets.GCP_SA_KEY }}
      - name: Build
        run: skaffold build --file-output=build.json --profile=ci
      - name: Deploy to Minikube
        run: skaffold deploy --build-artifacts=build.json --profile=ci
      - run: |-
          minikube service list
          minikube service api --url
          minikube service portal --url
          curl $(minikube service api --url)
          curl $(minikube service portal --url)
      - run: |-
          kubectl port-forward deploy/api 9001 &
          sleep 3
          curl -isSL http://localhost:9001/health
      - name: Render Kubernetes manifests
        run: skaffold render --build-artifacts=build.json --profile=ci --output=devbot.yaml
      # TODO: clone infrastructure repo, commit devbot.yaml for FluxCD to apply to cluster
